apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astro-code.fullname" . }}-config
  labels:
    {{- include "astro-code.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  PYTHON_BIN: {{ .Values.runtime.pythonBin | quote }}
{{- range $key, $value := .Values.configEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
