{{- if or .Values.opencode.serverPassword .Values.opencode.aiModelKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astro-code.fullname" . }}-secret
  labels:
    {{- include "astro-code.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.opencode.aiModelKey }}
  AI_MODEL_KEY: {{ .Values.opencode.aiModelKey | quote }}
{{- end }}
{{- if .Values.opencode.serverPassword }}
  OPENCODE_SERVER_PASSWORD: {{ .Values.opencode.serverPassword | quote }}
{{- end }}
{{- end }}
