image:
  repository: crpi-wixjy6gci86ms14e.cn-hongkong.personal.cr.aliyuncs.com/ay-dev/astro-code
  tag: v20260407-180800
  pullPolicy: Always


replicaCount: 1

ingress:
  enabled: false

service:
  type: NodePort
  nodePort: 31634

autoscaling:
  enabled: false

hostAliases:
  - ip: "192.168.31.111"
    hostnames:
      - "catalog.euclid.mcp.ay.dev"

opencodeConfig:
  mode: seed

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  config:
    enabled: true
    size: 1Gi
  data:
    enabled: true
    size: 1Gi
  workspace:
    enabled: true
    size: 5Gi

opencode:
  serverPassword: ""
  aiModelKey: "sk-ss"

extraEnv:
  - name: MCP_INSECURE_TLS
    value: "0"
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"
