image:
  repository: crpi-wixjy6gci86ms14e.cn-hongkong.personal.cr.aliyuncs.com/ay-dev/astro-code
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: crpi-regcred

replicaCount: 1

ingress:
  enabled: false

autoscaling:
  enabled: false

hostAliases:
  - ip: "192.168.31.111"
    hostnames:
      - "catalog.euclid.mcp.ay.dev"

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  config:
    enabled: true
    size: 1Gi
  data:
    enabled: true
    size: 1Gi
  workspace:
    enabled: true
    size: 5Gi

opencode:
  serverPassword: ""

opencodeConfig:
  secret:
    enabled: false
    create: false
    name: ""
    opencodeJson: ""

extraEnv:
  - name: MCP_INSECURE_TLS
    value: "1"
