langfuse:
  logging:
    level: info
    format: text
  nextauth:
    url: https://langfuse.ay.dev
    secret:
      value: "yv1fWuV7Xx58bFW22xCMj171DIK8QXY1LvJHRHNAVug="
  salt:
    value: "RS0rBPEGrhA587iOHpo9hgyu2uBhI6Yees1PaLnUhyc="
  encryptionKey:
    value: "11c57f084228f68e39d2fa4bb4d5cb28b4c7b8077db9e108dbc4b8f3b542b278"
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca-issuer
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    hosts:
      - host: langfuse.ay.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      enabled: true
      secretName: langfuse-tls

postgresql:
  deploy: true
  auth:
    password: "langfuse_pg_local_password"

redis:
  deploy: true
  auth:
    password: "langfuse_redis_local_password"

clickhouse:
  deploy: true
  auth:
    password: "langfuse_clickhouse_local_password"

s3:
  deploy: true
  auth:
    rootPassword: "langfuse_minio_local_password"
